import { Montserrat } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import "./globals.css";
import Providers from "@/redux/Provider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "SlangZee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={montserrat.className}>
          <Providers>
            <div>{children}</div>
          </Providers>
        </body>
      </UserProvider>
    </html>
  );
}
